### PR TITLE
Added service quota role

### PR DESCRIPTION
**Pull request by vitaliejicol**

### CODE REVIEW

**Comment by paulczar** [comment]
This looks great!   We should probably add a root level playbook to run it and then add it to the makefile so a person can run `make quota` before running `make create` if they want to run the quotas.

**Comment by vitaliejicol** [comment]
I think it is a good idea to have root level playbook, to support multi-aws-accounts (service quota check/openshift deploy) we can create an AWS profile at the playbook level for each aws account. I added just in case.

**Comment by vitaliejicol** [comment]
As part of the validation I would also include either in this role or another one:
`AWS SCP policies` check and check for service linked role `elasticloadbalancing.amazonaws.com`

**Comment by diana-sari** [comment]
reopen for testing

**Comment by diana-sari** [comment]
sorry please ignore this, we'll figure out another way of testing

**Comment by vitaliejicol** [comment]
@diana-sari Still looking for a way to test this?

**Comment by diana-sari** [comment]
sorry @vitaliejicol that comment i made was from a long time ago and i can't recall what that was all about again apologies😅

**Pull request merged**
